<?php

return [
    'plans' => [
        [
            'id' => 'basic-3',
            'name' => 'Basic',
            'duration_months' => 3,
            'price' => 750000,
            'formatted_price' => 'Rp 750.000',
            'period' => 'per 3 bulan',
            'is_featured' => false,
            'description' => 'Fitur esensial untuk manajemen pesantren.',
            'features' => [
                ['name' => 'Data Santri (Unlimited)', 'included' => true],
                ['name' => 'Keuangan SPP & Tabungan', 'included' => true],
                ['name' => 'Laporan Keuangan', 'included' => true],
                ['name' => 'WhatsApp Gateway', 'included' => false],
            ],
            'button_text' => 'Pilih Paket',
            'button_class' => 'btn-outline',
        ],
        [
            'id' => 'basic-6',
            'name' => 'Basic',
            'duration_months' => 6,
            'price' => 1500000,
            'formatted_price' => 'Rp 1.500.000',
            'period' => 'per 6 bulan',
            'is_featured' => false,
            'description' => 'Fitur esensial untuk manajemen pesantren.',
            'features' => [
                ['name' => 'Data Santri (Unlimited)', 'included' => true],
                ['name' => 'Keuangan SPP & Tabungan', 'included' => true],
                ['name' => 'Laporan Keuangan', 'included' => true],
                ['name' => 'WhatsApp Gateway', 'included' => false],
            ],
            'button_text' => 'Pilih Paket',
            'button_class' => 'btn-outline',
        ],
        [
            'id' => 'advance-3',
            'name' => 'Advance',
            'duration_months' => 3,
            'price' => 1500000,
            'formatted_price' => 'Rp 1.500.000',
            'period' => 'per 3 bulan',
            'is_featured' => false,
            'description' => 'Solusi lengkap dengan fitur prioritas.',
            'features' => [
                ['name' => 'Semua Fitur Basic', 'included' => true],
                ['name' => 'WhatsApp Gateway (Unlimited)', 'included' => true],
                ['name' => 'Billing Blast (Tagihan WA)', 'included' => true],
                ['name' => 'Kartu Santri Digital', 'included' => true],
                ['name' => 'Prioritas Support', 'included' => true],
            ],
            'button_text' => 'Pilih Advance',
            'button_class' => 'btn-primary',
        ],
        [
            'id' => 'advance-6',
            'name' => 'Advance',
            'duration_months' => 6,
            'price' => 3000000,
            'formatted_price' => 'Rp 3.000.000',
            'period' => 'per 6 bulan',
            'is_featured' => true,
            'description' => 'Solusi lengkap dengan fitur prioritas.',
            'features' => [
                ['name' => 'Semua Fitur Basic', 'included' => true],
                ['name' => 'WhatsApp Gateway (Unlimited)', 'included' => true],
                ['name' => 'Billing Blast (Tagihan WA)', 'included' => true],
                ['name' => 'Kartu Santri Digital', 'included' => true],
                ['name' => 'Prioritas Support', 'included' => true],
            ],
            'button_text' => 'Pilih Advance',
            'button_class' => 'btn-primary',
        ]
    ]
];
